package com.spring.mpvue.springbootmpvue.mybatis.po;

import java.util.Date;

public class Paramconfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paramconfig.id
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paramconfig.param1
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private String param1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paramconfig.param2
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private String param2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paramconfig.param3
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private String param3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paramconfig.param4
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private String param4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paramconfig.degree
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private String degree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paramconfig.update_time
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paramconfig.back1
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private String back1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paramconfig.back2
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private String back2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paramconfig.back3
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private Integer back3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paramconfig.back4
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private Integer back4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paramconfig.back5
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private Date back5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paramconfig.id
     *
     * @return the value of paramconfig.id
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paramconfig.id
     *
     * @param id the value for paramconfig.id
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paramconfig.param1
     *
     * @return the value of paramconfig.param1
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public String getParam1() {
        return param1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paramconfig.param1
     *
     * @param param1 the value for paramconfig.param1
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setParam1(String param1) {
        this.param1 = param1 == null ? null : param1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paramconfig.param2
     *
     * @return the value of paramconfig.param2
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public String getParam2() {
        return param2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paramconfig.param2
     *
     * @param param2 the value for paramconfig.param2
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setParam2(String param2) {
        this.param2 = param2 == null ? null : param2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paramconfig.param3
     *
     * @return the value of paramconfig.param3
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public String getParam3() {
        return param3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paramconfig.param3
     *
     * @param param3 the value for paramconfig.param3
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setParam3(String param3) {
        this.param3 = param3 == null ? null : param3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paramconfig.param4
     *
     * @return the value of paramconfig.param4
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public String getParam4() {
        return param4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paramconfig.param4
     *
     * @param param4 the value for paramconfig.param4
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setParam4(String param4) {
        this.param4 = param4 == null ? null : param4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paramconfig.degree
     *
     * @return the value of paramconfig.degree
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paramconfig.degree
     *
     * @param degree the value for paramconfig.degree
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setDegree(String degree) {
        this.degree = degree == null ? null : degree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paramconfig.update_time
     *
     * @return the value of paramconfig.update_time
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paramconfig.update_time
     *
     * @param updateTime the value for paramconfig.update_time
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paramconfig.back1
     *
     * @return the value of paramconfig.back1
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public String getBack1() {
        return back1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paramconfig.back1
     *
     * @param back1 the value for paramconfig.back1
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setBack1(String back1) {
        this.back1 = back1 == null ? null : back1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paramconfig.back2
     *
     * @return the value of paramconfig.back2
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public String getBack2() {
        return back2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paramconfig.back2
     *
     * @param back2 the value for paramconfig.back2
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setBack2(String back2) {
        this.back2 = back2 == null ? null : back2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paramconfig.back3
     *
     * @return the value of paramconfig.back3
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public Integer getBack3() {
        return back3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paramconfig.back3
     *
     * @param back3 the value for paramconfig.back3
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setBack3(Integer back3) {
        this.back3 = back3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paramconfig.back4
     *
     * @return the value of paramconfig.back4
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public Integer getBack4() {
        return back4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paramconfig.back4
     *
     * @param back4 the value for paramconfig.back4
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setBack4(Integer back4) {
        this.back4 = back4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paramconfig.back5
     *
     * @return the value of paramconfig.back5
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public Date getBack5() {
        return back5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paramconfig.back5
     *
     * @param back5 the value for paramconfig.back5
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setBack5(Date back5) {
        this.back5 = back5;
    }
}