package com.spring.mpvue.springbootmpvue.mybatis.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table record
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table record
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table record
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public RecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table record
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOpenIdIsNull() {
            addCriterion("open_id is null");
            return (Criteria) this;
        }

        public Criteria andOpenIdIsNotNull() {
            addCriterion("open_id is not null");
            return (Criteria) this;
        }

        public Criteria andOpenIdEqualTo(String value) {
            addCriterion("open_id =", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdNotEqualTo(String value) {
            addCriterion("open_id <>", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdGreaterThan(String value) {
            addCriterion("open_id >", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdGreaterThanOrEqualTo(String value) {
            addCriterion("open_id >=", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdLessThan(String value) {
            addCriterion("open_id <", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdLessThanOrEqualTo(String value) {
            addCriterion("open_id <=", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdLike(String value) {
            addCriterion("open_id like", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdNotLike(String value) {
            addCriterion("open_id not like", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdIn(List<String> values) {
            addCriterion("open_id in", values, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdNotIn(List<String> values) {
            addCriterion("open_id not in", values, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdBetween(String value1, String value2) {
            addCriterion("open_id between", value1, value2, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdNotBetween(String value1, String value2) {
            addCriterion("open_id not between", value1, value2, "openId");
            return (Criteria) this;
        }

        public Criteria andQueryResultIsNull() {
            addCriterion("query_result is null");
            return (Criteria) this;
        }

        public Criteria andQueryResultIsNotNull() {
            addCriterion("query_result is not null");
            return (Criteria) this;
        }

        public Criteria andQueryResultEqualTo(String value) {
            addCriterion("query_result =", value, "queryResult");
            return (Criteria) this;
        }

        public Criteria andQueryResultNotEqualTo(String value) {
            addCriterion("query_result <>", value, "queryResult");
            return (Criteria) this;
        }

        public Criteria andQueryResultGreaterThan(String value) {
            addCriterion("query_result >", value, "queryResult");
            return (Criteria) this;
        }

        public Criteria andQueryResultGreaterThanOrEqualTo(String value) {
            addCriterion("query_result >=", value, "queryResult");
            return (Criteria) this;
        }

        public Criteria andQueryResultLessThan(String value) {
            addCriterion("query_result <", value, "queryResult");
            return (Criteria) this;
        }

        public Criteria andQueryResultLessThanOrEqualTo(String value) {
            addCriterion("query_result <=", value, "queryResult");
            return (Criteria) this;
        }

        public Criteria andQueryResultLike(String value) {
            addCriterion("query_result like", value, "queryResult");
            return (Criteria) this;
        }

        public Criteria andQueryResultNotLike(String value) {
            addCriterion("query_result not like", value, "queryResult");
            return (Criteria) this;
        }

        public Criteria andQueryResultIn(List<String> values) {
            addCriterion("query_result in", values, "queryResult");
            return (Criteria) this;
        }

        public Criteria andQueryResultNotIn(List<String> values) {
            addCriterion("query_result not in", values, "queryResult");
            return (Criteria) this;
        }

        public Criteria andQueryResultBetween(String value1, String value2) {
            addCriterion("query_result between", value1, value2, "queryResult");
            return (Criteria) this;
        }

        public Criteria andQueryResultNotBetween(String value1, String value2) {
            addCriterion("query_result not between", value1, value2, "queryResult");
            return (Criteria) this;
        }

        public Criteria andDetailAddressIsNull() {
            addCriterion("detail_address is null");
            return (Criteria) this;
        }

        public Criteria andDetailAddressIsNotNull() {
            addCriterion("detail_address is not null");
            return (Criteria) this;
        }

        public Criteria andDetailAddressEqualTo(String value) {
            addCriterion("detail_address =", value, "detailAddress");
            return (Criteria) this;
        }

        public Criteria andDetailAddressNotEqualTo(String value) {
            addCriterion("detail_address <>", value, "detailAddress");
            return (Criteria) this;
        }

        public Criteria andDetailAddressGreaterThan(String value) {
            addCriterion("detail_address >", value, "detailAddress");
            return (Criteria) this;
        }

        public Criteria andDetailAddressGreaterThanOrEqualTo(String value) {
            addCriterion("detail_address >=", value, "detailAddress");
            return (Criteria) this;
        }

        public Criteria andDetailAddressLessThan(String value) {
            addCriterion("detail_address <", value, "detailAddress");
            return (Criteria) this;
        }

        public Criteria andDetailAddressLessThanOrEqualTo(String value) {
            addCriterion("detail_address <=", value, "detailAddress");
            return (Criteria) this;
        }

        public Criteria andDetailAddressLike(String value) {
            addCriterion("detail_address like", value, "detailAddress");
            return (Criteria) this;
        }

        public Criteria andDetailAddressNotLike(String value) {
            addCriterion("detail_address not like", value, "detailAddress");
            return (Criteria) this;
        }

        public Criteria andDetailAddressIn(List<String> values) {
            addCriterion("detail_address in", values, "detailAddress");
            return (Criteria) this;
        }

        public Criteria andDetailAddressNotIn(List<String> values) {
            addCriterion("detail_address not in", values, "detailAddress");
            return (Criteria) this;
        }

        public Criteria andDetailAddressBetween(String value1, String value2) {
            addCriterion("detail_address between", value1, value2, "detailAddress");
            return (Criteria) this;
        }

        public Criteria andDetailAddressNotBetween(String value1, String value2) {
            addCriterion("detail_address not between", value1, value2, "detailAddress");
            return (Criteria) this;
        }

        public Criteria andBuildTypeIsNull() {
            addCriterion("build_type is null");
            return (Criteria) this;
        }

        public Criteria andBuildTypeIsNotNull() {
            addCriterion("build_type is not null");
            return (Criteria) this;
        }

        public Criteria andBuildTypeEqualTo(String value) {
            addCriterion("build_type =", value, "buildType");
            return (Criteria) this;
        }

        public Criteria andBuildTypeNotEqualTo(String value) {
            addCriterion("build_type <>", value, "buildType");
            return (Criteria) this;
        }

        public Criteria andBuildTypeGreaterThan(String value) {
            addCriterion("build_type >", value, "buildType");
            return (Criteria) this;
        }

        public Criteria andBuildTypeGreaterThanOrEqualTo(String value) {
            addCriterion("build_type >=", value, "buildType");
            return (Criteria) this;
        }

        public Criteria andBuildTypeLessThan(String value) {
            addCriterion("build_type <", value, "buildType");
            return (Criteria) this;
        }

        public Criteria andBuildTypeLessThanOrEqualTo(String value) {
            addCriterion("build_type <=", value, "buildType");
            return (Criteria) this;
        }

        public Criteria andBuildTypeLike(String value) {
            addCriterion("build_type like", value, "buildType");
            return (Criteria) this;
        }

        public Criteria andBuildTypeNotLike(String value) {
            addCriterion("build_type not like", value, "buildType");
            return (Criteria) this;
        }

        public Criteria andBuildTypeIn(List<String> values) {
            addCriterion("build_type in", values, "buildType");
            return (Criteria) this;
        }

        public Criteria andBuildTypeNotIn(List<String> values) {
            addCriterion("build_type not in", values, "buildType");
            return (Criteria) this;
        }

        public Criteria andBuildTypeBetween(String value1, String value2) {
            addCriterion("build_type between", value1, value2, "buildType");
            return (Criteria) this;
        }

        public Criteria andBuildTypeNotBetween(String value1, String value2) {
            addCriterion("build_type not between", value1, value2, "buildType");
            return (Criteria) this;
        }

        public Criteria andAreaIsNull() {
            addCriterion("area is null");
            return (Criteria) this;
        }

        public Criteria andAreaIsNotNull() {
            addCriterion("area is not null");
            return (Criteria) this;
        }

        public Criteria andAreaEqualTo(String value) {
            addCriterion("area =", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotEqualTo(String value) {
            addCriterion("area <>", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThan(String value) {
            addCriterion("area >", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThanOrEqualTo(String value) {
            addCriterion("area >=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThan(String value) {
            addCriterion("area <", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThanOrEqualTo(String value) {
            addCriterion("area <=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLike(String value) {
            addCriterion("area like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotLike(String value) {
            addCriterion("area not like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaIn(List<String> values) {
            addCriterion("area in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotIn(List<String> values) {
            addCriterion("area not in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaBetween(String value1, String value2) {
            addCriterion("area between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotBetween(String value1, String value2) {
            addCriterion("area not between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andHouseTypeIsNull() {
            addCriterion("house_type is null");
            return (Criteria) this;
        }

        public Criteria andHouseTypeIsNotNull() {
            addCriterion("house_type is not null");
            return (Criteria) this;
        }

        public Criteria andHouseTypeEqualTo(String value) {
            addCriterion("house_type =", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeNotEqualTo(String value) {
            addCriterion("house_type <>", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeGreaterThan(String value) {
            addCriterion("house_type >", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeGreaterThanOrEqualTo(String value) {
            addCriterion("house_type >=", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeLessThan(String value) {
            addCriterion("house_type <", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeLessThanOrEqualTo(String value) {
            addCriterion("house_type <=", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeLike(String value) {
            addCriterion("house_type like", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeNotLike(String value) {
            addCriterion("house_type not like", value, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeIn(List<String> values) {
            addCriterion("house_type in", values, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeNotIn(List<String> values) {
            addCriterion("house_type not in", values, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeBetween(String value1, String value2) {
            addCriterion("house_type between", value1, value2, "houseType");
            return (Criteria) this;
        }

        public Criteria andHouseTypeNotBetween(String value1, String value2) {
            addCriterion("house_type not between", value1, value2, "houseType");
            return (Criteria) this;
        }

        public Criteria andIndoorStructureIsNull() {
            addCriterion("indoor_structure is null");
            return (Criteria) this;
        }

        public Criteria andIndoorStructureIsNotNull() {
            addCriterion("indoor_structure is not null");
            return (Criteria) this;
        }

        public Criteria andIndoorStructureEqualTo(String value) {
            addCriterion("indoor_structure =", value, "indoorStructure");
            return (Criteria) this;
        }

        public Criteria andIndoorStructureNotEqualTo(String value) {
            addCriterion("indoor_structure <>", value, "indoorStructure");
            return (Criteria) this;
        }

        public Criteria andIndoorStructureGreaterThan(String value) {
            addCriterion("indoor_structure >", value, "indoorStructure");
            return (Criteria) this;
        }

        public Criteria andIndoorStructureGreaterThanOrEqualTo(String value) {
            addCriterion("indoor_structure >=", value, "indoorStructure");
            return (Criteria) this;
        }

        public Criteria andIndoorStructureLessThan(String value) {
            addCriterion("indoor_structure <", value, "indoorStructure");
            return (Criteria) this;
        }

        public Criteria andIndoorStructureLessThanOrEqualTo(String value) {
            addCriterion("indoor_structure <=", value, "indoorStructure");
            return (Criteria) this;
        }

        public Criteria andIndoorStructureLike(String value) {
            addCriterion("indoor_structure like", value, "indoorStructure");
            return (Criteria) this;
        }

        public Criteria andIndoorStructureNotLike(String value) {
            addCriterion("indoor_structure not like", value, "indoorStructure");
            return (Criteria) this;
        }

        public Criteria andIndoorStructureIn(List<String> values) {
            addCriterion("indoor_structure in", values, "indoorStructure");
            return (Criteria) this;
        }

        public Criteria andIndoorStructureNotIn(List<String> values) {
            addCriterion("indoor_structure not in", values, "indoorStructure");
            return (Criteria) this;
        }

        public Criteria andIndoorStructureBetween(String value1, String value2) {
            addCriterion("indoor_structure between", value1, value2, "indoorStructure");
            return (Criteria) this;
        }

        public Criteria andIndoorStructureNotBetween(String value1, String value2) {
            addCriterion("indoor_structure not between", value1, value2, "indoorStructure");
            return (Criteria) this;
        }

        public Criteria andFloorIsNull() {
            addCriterion("floor is null");
            return (Criteria) this;
        }

        public Criteria andFloorIsNotNull() {
            addCriterion("floor is not null");
            return (Criteria) this;
        }

        public Criteria andFloorEqualTo(String value) {
            addCriterion("floor =", value, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorNotEqualTo(String value) {
            addCriterion("floor <>", value, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorGreaterThan(String value) {
            addCriterion("floor >", value, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorGreaterThanOrEqualTo(String value) {
            addCriterion("floor >=", value, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorLessThan(String value) {
            addCriterion("floor <", value, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorLessThanOrEqualTo(String value) {
            addCriterion("floor <=", value, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorLike(String value) {
            addCriterion("floor like", value, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorNotLike(String value) {
            addCriterion("floor not like", value, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorIn(List<String> values) {
            addCriterion("floor in", values, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorNotIn(List<String> values) {
            addCriterion("floor not in", values, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorBetween(String value1, String value2) {
            addCriterion("floor between", value1, value2, "floor");
            return (Criteria) this;
        }

        public Criteria andFloorNotBetween(String value1, String value2) {
            addCriterion("floor not between", value1, value2, "floor");
            return (Criteria) this;
        }

        public Criteria andOrientationIsNull() {
            addCriterion("orientation is null");
            return (Criteria) this;
        }

        public Criteria andOrientationIsNotNull() {
            addCriterion("orientation is not null");
            return (Criteria) this;
        }

        public Criteria andOrientationEqualTo(String value) {
            addCriterion("orientation =", value, "orientation");
            return (Criteria) this;
        }

        public Criteria andOrientationNotEqualTo(String value) {
            addCriterion("orientation <>", value, "orientation");
            return (Criteria) this;
        }

        public Criteria andOrientationGreaterThan(String value) {
            addCriterion("orientation >", value, "orientation");
            return (Criteria) this;
        }

        public Criteria andOrientationGreaterThanOrEqualTo(String value) {
            addCriterion("orientation >=", value, "orientation");
            return (Criteria) this;
        }

        public Criteria andOrientationLessThan(String value) {
            addCriterion("orientation <", value, "orientation");
            return (Criteria) this;
        }

        public Criteria andOrientationLessThanOrEqualTo(String value) {
            addCriterion("orientation <=", value, "orientation");
            return (Criteria) this;
        }

        public Criteria andOrientationLike(String value) {
            addCriterion("orientation like", value, "orientation");
            return (Criteria) this;
        }

        public Criteria andOrientationNotLike(String value) {
            addCriterion("orientation not like", value, "orientation");
            return (Criteria) this;
        }

        public Criteria andOrientationIn(List<String> values) {
            addCriterion("orientation in", values, "orientation");
            return (Criteria) this;
        }

        public Criteria andOrientationNotIn(List<String> values) {
            addCriterion("orientation not in", values, "orientation");
            return (Criteria) this;
        }

        public Criteria andOrientationBetween(String value1, String value2) {
            addCriterion("orientation between", value1, value2, "orientation");
            return (Criteria) this;
        }

        public Criteria andOrientationNotBetween(String value1, String value2) {
            addCriterion("orientation not between", value1, value2, "orientation");
            return (Criteria) this;
        }

        public Criteria andDegreeDecorationIsNull() {
            addCriterion("degree_decoration is null");
            return (Criteria) this;
        }

        public Criteria andDegreeDecorationIsNotNull() {
            addCriterion("degree_decoration is not null");
            return (Criteria) this;
        }

        public Criteria andDegreeDecorationEqualTo(String value) {
            addCriterion("degree_decoration =", value, "degreeDecoration");
            return (Criteria) this;
        }

        public Criteria andDegreeDecorationNotEqualTo(String value) {
            addCriterion("degree_decoration <>", value, "degreeDecoration");
            return (Criteria) this;
        }

        public Criteria andDegreeDecorationGreaterThan(String value) {
            addCriterion("degree_decoration >", value, "degreeDecoration");
            return (Criteria) this;
        }

        public Criteria andDegreeDecorationGreaterThanOrEqualTo(String value) {
            addCriterion("degree_decoration >=", value, "degreeDecoration");
            return (Criteria) this;
        }

        public Criteria andDegreeDecorationLessThan(String value) {
            addCriterion("degree_decoration <", value, "degreeDecoration");
            return (Criteria) this;
        }

        public Criteria andDegreeDecorationLessThanOrEqualTo(String value) {
            addCriterion("degree_decoration <=", value, "degreeDecoration");
            return (Criteria) this;
        }

        public Criteria andDegreeDecorationLike(String value) {
            addCriterion("degree_decoration like", value, "degreeDecoration");
            return (Criteria) this;
        }

        public Criteria andDegreeDecorationNotLike(String value) {
            addCriterion("degree_decoration not like", value, "degreeDecoration");
            return (Criteria) this;
        }

        public Criteria andDegreeDecorationIn(List<String> values) {
            addCriterion("degree_decoration in", values, "degreeDecoration");
            return (Criteria) this;
        }

        public Criteria andDegreeDecorationNotIn(List<String> values) {
            addCriterion("degree_decoration not in", values, "degreeDecoration");
            return (Criteria) this;
        }

        public Criteria andDegreeDecorationBetween(String value1, String value2) {
            addCriterion("degree_decoration between", value1, value2, "degreeDecoration");
            return (Criteria) this;
        }

        public Criteria andDegreeDecorationNotBetween(String value1, String value2) {
            addCriterion("degree_decoration not between", value1, value2, "degreeDecoration");
            return (Criteria) this;
        }

        public Criteria andBuildYearIsNull() {
            addCriterion("build_year is null");
            return (Criteria) this;
        }

        public Criteria andBuildYearIsNotNull() {
            addCriterion("build_year is not null");
            return (Criteria) this;
        }

        public Criteria andBuildYearEqualTo(String value) {
            addCriterion("build_year =", value, "buildYear");
            return (Criteria) this;
        }

        public Criteria andBuildYearNotEqualTo(String value) {
            addCriterion("build_year <>", value, "buildYear");
            return (Criteria) this;
        }

        public Criteria andBuildYearGreaterThan(String value) {
            addCriterion("build_year >", value, "buildYear");
            return (Criteria) this;
        }

        public Criteria andBuildYearGreaterThanOrEqualTo(String value) {
            addCriterion("build_year >=", value, "buildYear");
            return (Criteria) this;
        }

        public Criteria andBuildYearLessThan(String value) {
            addCriterion("build_year <", value, "buildYear");
            return (Criteria) this;
        }

        public Criteria andBuildYearLessThanOrEqualTo(String value) {
            addCriterion("build_year <=", value, "buildYear");
            return (Criteria) this;
        }

        public Criteria andBuildYearLike(String value) {
            addCriterion("build_year like", value, "buildYear");
            return (Criteria) this;
        }

        public Criteria andBuildYearNotLike(String value) {
            addCriterion("build_year not like", value, "buildYear");
            return (Criteria) this;
        }

        public Criteria andBuildYearIn(List<String> values) {
            addCriterion("build_year in", values, "buildYear");
            return (Criteria) this;
        }

        public Criteria andBuildYearNotIn(List<String> values) {
            addCriterion("build_year not in", values, "buildYear");
            return (Criteria) this;
        }

        public Criteria andBuildYearBetween(String value1, String value2) {
            addCriterion("build_year between", value1, value2, "buildYear");
            return (Criteria) this;
        }

        public Criteria andBuildYearNotBetween(String value1, String value2) {
            addCriterion("build_year not between", value1, value2, "buildYear");
            return (Criteria) this;
        }

        public Criteria andOwnStatusIsNull() {
            addCriterion("own_status is null");
            return (Criteria) this;
        }

        public Criteria andOwnStatusIsNotNull() {
            addCriterion("own_status is not null");
            return (Criteria) this;
        }

        public Criteria andOwnStatusEqualTo(String value) {
            addCriterion("own_status =", value, "ownStatus");
            return (Criteria) this;
        }

        public Criteria andOwnStatusNotEqualTo(String value) {
            addCriterion("own_status <>", value, "ownStatus");
            return (Criteria) this;
        }

        public Criteria andOwnStatusGreaterThan(String value) {
            addCriterion("own_status >", value, "ownStatus");
            return (Criteria) this;
        }

        public Criteria andOwnStatusGreaterThanOrEqualTo(String value) {
            addCriterion("own_status >=", value, "ownStatus");
            return (Criteria) this;
        }

        public Criteria andOwnStatusLessThan(String value) {
            addCriterion("own_status <", value, "ownStatus");
            return (Criteria) this;
        }

        public Criteria andOwnStatusLessThanOrEqualTo(String value) {
            addCriterion("own_status <=", value, "ownStatus");
            return (Criteria) this;
        }

        public Criteria andOwnStatusLike(String value) {
            addCriterion("own_status like", value, "ownStatus");
            return (Criteria) this;
        }

        public Criteria andOwnStatusNotLike(String value) {
            addCriterion("own_status not like", value, "ownStatus");
            return (Criteria) this;
        }

        public Criteria andOwnStatusIn(List<String> values) {
            addCriterion("own_status in", values, "ownStatus");
            return (Criteria) this;
        }

        public Criteria andOwnStatusNotIn(List<String> values) {
            addCriterion("own_status not in", values, "ownStatus");
            return (Criteria) this;
        }

        public Criteria andOwnStatusBetween(String value1, String value2) {
            addCriterion("own_status between", value1, value2, "ownStatus");
            return (Criteria) this;
        }

        public Criteria andOwnStatusNotBetween(String value1, String value2) {
            addCriterion("own_status not between", value1, value2, "ownStatus");
            return (Criteria) this;
        }

        public Criteria andQueryDateIsNull() {
            addCriterion("query_date is null");
            return (Criteria) this;
        }

        public Criteria andQueryDateIsNotNull() {
            addCriterion("query_date is not null");
            return (Criteria) this;
        }

        public Criteria andQueryDateEqualTo(Date value) {
            addCriterion("query_date =", value, "queryDate");
            return (Criteria) this;
        }

        public Criteria andQueryDateNotEqualTo(Date value) {
            addCriterion("query_date <>", value, "queryDate");
            return (Criteria) this;
        }

        public Criteria andQueryDateGreaterThan(Date value) {
            addCriterion("query_date >", value, "queryDate");
            return (Criteria) this;
        }

        public Criteria andQueryDateGreaterThanOrEqualTo(Date value) {
            addCriterion("query_date >=", value, "queryDate");
            return (Criteria) this;
        }

        public Criteria andQueryDateLessThan(Date value) {
            addCriterion("query_date <", value, "queryDate");
            return (Criteria) this;
        }

        public Criteria andQueryDateLessThanOrEqualTo(Date value) {
            addCriterion("query_date <=", value, "queryDate");
            return (Criteria) this;
        }

        public Criteria andQueryDateIn(List<Date> values) {
            addCriterion("query_date in", values, "queryDate");
            return (Criteria) this;
        }

        public Criteria andQueryDateNotIn(List<Date> values) {
            addCriterion("query_date not in", values, "queryDate");
            return (Criteria) this;
        }

        public Criteria andQueryDateBetween(Date value1, Date value2) {
            addCriterion("query_date between", value1, value2, "queryDate");
            return (Criteria) this;
        }

        public Criteria andQueryDateNotBetween(Date value1, Date value2) {
            addCriterion("query_date not between", value1, value2, "queryDate");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("del_flag is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("del_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(String value) {
            addCriterion("del_flag =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(String value) {
            addCriterion("del_flag <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(String value) {
            addCriterion("del_flag >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(String value) {
            addCriterion("del_flag >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(String value) {
            addCriterion("del_flag <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(String value) {
            addCriterion("del_flag <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLike(String value) {
            addCriterion("del_flag like", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotLike(String value) {
            addCriterion("del_flag not like", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<String> values) {
            addCriterion("del_flag in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<String> values) {
            addCriterion("del_flag not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(String value1, String value2) {
            addCriterion("del_flag between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(String value1, String value2) {
            addCriterion("del_flag not between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDissentIsNull() {
            addCriterion("dissent is null");
            return (Criteria) this;
        }

        public Criteria andDissentIsNotNull() {
            addCriterion("dissent is not null");
            return (Criteria) this;
        }

        public Criteria andDissentEqualTo(String value) {
            addCriterion("dissent =", value, "dissent");
            return (Criteria) this;
        }

        public Criteria andDissentNotEqualTo(String value) {
            addCriterion("dissent <>", value, "dissent");
            return (Criteria) this;
        }

        public Criteria andDissentGreaterThan(String value) {
            addCriterion("dissent >", value, "dissent");
            return (Criteria) this;
        }

        public Criteria andDissentGreaterThanOrEqualTo(String value) {
            addCriterion("dissent >=", value, "dissent");
            return (Criteria) this;
        }

        public Criteria andDissentLessThan(String value) {
            addCriterion("dissent <", value, "dissent");
            return (Criteria) this;
        }

        public Criteria andDissentLessThanOrEqualTo(String value) {
            addCriterion("dissent <=", value, "dissent");
            return (Criteria) this;
        }

        public Criteria andDissentLike(String value) {
            addCriterion("dissent like", value, "dissent");
            return (Criteria) this;
        }

        public Criteria andDissentNotLike(String value) {
            addCriterion("dissent not like", value, "dissent");
            return (Criteria) this;
        }

        public Criteria andDissentIn(List<String> values) {
            addCriterion("dissent in", values, "dissent");
            return (Criteria) this;
        }

        public Criteria andDissentNotIn(List<String> values) {
            addCriterion("dissent not in", values, "dissent");
            return (Criteria) this;
        }

        public Criteria andDissentBetween(String value1, String value2) {
            addCriterion("dissent between", value1, value2, "dissent");
            return (Criteria) this;
        }

        public Criteria andDissentNotBetween(String value1, String value2) {
            addCriterion("dissent not between", value1, value2, "dissent");
            return (Criteria) this;
        }

        public Criteria andExpectedPriceIsNull() {
            addCriterion("expected_price is null");
            return (Criteria) this;
        }

        public Criteria andExpectedPriceIsNotNull() {
            addCriterion("expected_price is not null");
            return (Criteria) this;
        }

        public Criteria andExpectedPriceEqualTo(String value) {
            addCriterion("expected_price =", value, "expectedPrice");
            return (Criteria) this;
        }

        public Criteria andExpectedPriceNotEqualTo(String value) {
            addCriterion("expected_price <>", value, "expectedPrice");
            return (Criteria) this;
        }

        public Criteria andExpectedPriceGreaterThan(String value) {
            addCriterion("expected_price >", value, "expectedPrice");
            return (Criteria) this;
        }

        public Criteria andExpectedPriceGreaterThanOrEqualTo(String value) {
            addCriterion("expected_price >=", value, "expectedPrice");
            return (Criteria) this;
        }

        public Criteria andExpectedPriceLessThan(String value) {
            addCriterion("expected_price <", value, "expectedPrice");
            return (Criteria) this;
        }

        public Criteria andExpectedPriceLessThanOrEqualTo(String value) {
            addCriterion("expected_price <=", value, "expectedPrice");
            return (Criteria) this;
        }

        public Criteria andExpectedPriceLike(String value) {
            addCriterion("expected_price like", value, "expectedPrice");
            return (Criteria) this;
        }

        public Criteria andExpectedPriceNotLike(String value) {
            addCriterion("expected_price not like", value, "expectedPrice");
            return (Criteria) this;
        }

        public Criteria andExpectedPriceIn(List<String> values) {
            addCriterion("expected_price in", values, "expectedPrice");
            return (Criteria) this;
        }

        public Criteria andExpectedPriceNotIn(List<String> values) {
            addCriterion("expected_price not in", values, "expectedPrice");
            return (Criteria) this;
        }

        public Criteria andExpectedPriceBetween(String value1, String value2) {
            addCriterion("expected_price between", value1, value2, "expectedPrice");
            return (Criteria) this;
        }

        public Criteria andExpectedPriceNotBetween(String value1, String value2) {
            addCriterion("expected_price not between", value1, value2, "expectedPrice");
            return (Criteria) this;
        }

        public Criteria andDissentReasonIsNull() {
            addCriterion("dissent_reason is null");
            return (Criteria) this;
        }

        public Criteria andDissentReasonIsNotNull() {
            addCriterion("dissent_reason is not null");
            return (Criteria) this;
        }

        public Criteria andDissentReasonEqualTo(String value) {
            addCriterion("dissent_reason =", value, "dissentReason");
            return (Criteria) this;
        }

        public Criteria andDissentReasonNotEqualTo(String value) {
            addCriterion("dissent_reason <>", value, "dissentReason");
            return (Criteria) this;
        }

        public Criteria andDissentReasonGreaterThan(String value) {
            addCriterion("dissent_reason >", value, "dissentReason");
            return (Criteria) this;
        }

        public Criteria andDissentReasonGreaterThanOrEqualTo(String value) {
            addCriterion("dissent_reason >=", value, "dissentReason");
            return (Criteria) this;
        }

        public Criteria andDissentReasonLessThan(String value) {
            addCriterion("dissent_reason <", value, "dissentReason");
            return (Criteria) this;
        }

        public Criteria andDissentReasonLessThanOrEqualTo(String value) {
            addCriterion("dissent_reason <=", value, "dissentReason");
            return (Criteria) this;
        }

        public Criteria andDissentReasonLike(String value) {
            addCriterion("dissent_reason like", value, "dissentReason");
            return (Criteria) this;
        }

        public Criteria andDissentReasonNotLike(String value) {
            addCriterion("dissent_reason not like", value, "dissentReason");
            return (Criteria) this;
        }

        public Criteria andDissentReasonIn(List<String> values) {
            addCriterion("dissent_reason in", values, "dissentReason");
            return (Criteria) this;
        }

        public Criteria andDissentReasonNotIn(List<String> values) {
            addCriterion("dissent_reason not in", values, "dissentReason");
            return (Criteria) this;
        }

        public Criteria andDissentReasonBetween(String value1, String value2) {
            addCriterion("dissent_reason between", value1, value2, "dissentReason");
            return (Criteria) this;
        }

        public Criteria andDissentReasonNotBetween(String value1, String value2) {
            addCriterion("dissent_reason not between", value1, value2, "dissentReason");
            return (Criteria) this;
        }

        public Criteria andBack1IsNull() {
            addCriterion("back1 is null");
            return (Criteria) this;
        }

        public Criteria andBack1IsNotNull() {
            addCriterion("back1 is not null");
            return (Criteria) this;
        }

        public Criteria andBack1EqualTo(String value) {
            addCriterion("back1 =", value, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1NotEqualTo(String value) {
            addCriterion("back1 <>", value, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1GreaterThan(String value) {
            addCriterion("back1 >", value, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1GreaterThanOrEqualTo(String value) {
            addCriterion("back1 >=", value, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1LessThan(String value) {
            addCriterion("back1 <", value, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1LessThanOrEqualTo(String value) {
            addCriterion("back1 <=", value, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1Like(String value) {
            addCriterion("back1 like", value, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1NotLike(String value) {
            addCriterion("back1 not like", value, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1In(List<String> values) {
            addCriterion("back1 in", values, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1NotIn(List<String> values) {
            addCriterion("back1 not in", values, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1Between(String value1, String value2) {
            addCriterion("back1 between", value1, value2, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1NotBetween(String value1, String value2) {
            addCriterion("back1 not between", value1, value2, "back1");
            return (Criteria) this;
        }

        public Criteria andBack2IsNull() {
            addCriterion("back2 is null");
            return (Criteria) this;
        }

        public Criteria andBack2IsNotNull() {
            addCriterion("back2 is not null");
            return (Criteria) this;
        }

        public Criteria andBack2EqualTo(Date value) {
            addCriterion("back2 =", value, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2NotEqualTo(Date value) {
            addCriterion("back2 <>", value, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2GreaterThan(Date value) {
            addCriterion("back2 >", value, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2GreaterThanOrEqualTo(Date value) {
            addCriterion("back2 >=", value, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2LessThan(Date value) {
            addCriterion("back2 <", value, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2LessThanOrEqualTo(Date value) {
            addCriterion("back2 <=", value, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2In(List<Date> values) {
            addCriterion("back2 in", values, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2NotIn(List<Date> values) {
            addCriterion("back2 not in", values, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2Between(Date value1, Date value2) {
            addCriterion("back2 between", value1, value2, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2NotBetween(Date value1, Date value2) {
            addCriterion("back2 not between", value1, value2, "back2");
            return (Criteria) this;
        }

        public Criteria andBack3IsNull() {
            addCriterion("back3 is null");
            return (Criteria) this;
        }

        public Criteria andBack3IsNotNull() {
            addCriterion("back3 is not null");
            return (Criteria) this;
        }

        public Criteria andBack3EqualTo(String value) {
            addCriterion("back3 =", value, "back3");
            return (Criteria) this;
        }

        public Criteria andBack3NotEqualTo(String value) {
            addCriterion("back3 <>", value, "back3");
            return (Criteria) this;
        }

        public Criteria andBack3GreaterThan(String value) {
            addCriterion("back3 >", value, "back3");
            return (Criteria) this;
        }

        public Criteria andBack3GreaterThanOrEqualTo(String value) {
            addCriterion("back3 >=", value, "back3");
            return (Criteria) this;
        }

        public Criteria andBack3LessThan(String value) {
            addCriterion("back3 <", value, "back3");
            return (Criteria) this;
        }

        public Criteria andBack3LessThanOrEqualTo(String value) {
            addCriterion("back3 <=", value, "back3");
            return (Criteria) this;
        }

        public Criteria andBack3Like(String value) {
            addCriterion("back3 like", value, "back3");
            return (Criteria) this;
        }

        public Criteria andBack3NotLike(String value) {
            addCriterion("back3 not like", value, "back3");
            return (Criteria) this;
        }

        public Criteria andBack3In(List<String> values) {
            addCriterion("back3 in", values, "back3");
            return (Criteria) this;
        }

        public Criteria andBack3NotIn(List<String> values) {
            addCriterion("back3 not in", values, "back3");
            return (Criteria) this;
        }

        public Criteria andBack3Between(String value1, String value2) {
            addCriterion("back3 between", value1, value2, "back3");
            return (Criteria) this;
        }

        public Criteria andBack3NotBetween(String value1, String value2) {
            addCriterion("back3 not between", value1, value2, "back3");
            return (Criteria) this;
        }

        public Criteria andBack4IsNull() {
            addCriterion("back4 is null");
            return (Criteria) this;
        }

        public Criteria andBack4IsNotNull() {
            addCriterion("back4 is not null");
            return (Criteria) this;
        }

        public Criteria andBack4EqualTo(String value) {
            addCriterion("back4 =", value, "back4");
            return (Criteria) this;
        }

        public Criteria andBack4NotEqualTo(String value) {
            addCriterion("back4 <>", value, "back4");
            return (Criteria) this;
        }

        public Criteria andBack4GreaterThan(String value) {
            addCriterion("back4 >", value, "back4");
            return (Criteria) this;
        }

        public Criteria andBack4GreaterThanOrEqualTo(String value) {
            addCriterion("back4 >=", value, "back4");
            return (Criteria) this;
        }

        public Criteria andBack4LessThan(String value) {
            addCriterion("back4 <", value, "back4");
            return (Criteria) this;
        }

        public Criteria andBack4LessThanOrEqualTo(String value) {
            addCriterion("back4 <=", value, "back4");
            return (Criteria) this;
        }

        public Criteria andBack4Like(String value) {
            addCriterion("back4 like", value, "back4");
            return (Criteria) this;
        }

        public Criteria andBack4NotLike(String value) {
            addCriterion("back4 not like", value, "back4");
            return (Criteria) this;
        }

        public Criteria andBack4In(List<String> values) {
            addCriterion("back4 in", values, "back4");
            return (Criteria) this;
        }

        public Criteria andBack4NotIn(List<String> values) {
            addCriterion("back4 not in", values, "back4");
            return (Criteria) this;
        }

        public Criteria andBack4Between(String value1, String value2) {
            addCriterion("back4 between", value1, value2, "back4");
            return (Criteria) this;
        }

        public Criteria andBack4NotBetween(String value1, String value2) {
            addCriterion("back4 not between", value1, value2, "back4");
            return (Criteria) this;
        }

        public Criteria andBack5IsNull() {
            addCriterion("back5 is null");
            return (Criteria) this;
        }

        public Criteria andBack5IsNotNull() {
            addCriterion("back5 is not null");
            return (Criteria) this;
        }

        public Criteria andBack5EqualTo(String value) {
            addCriterion("back5 =", value, "back5");
            return (Criteria) this;
        }

        public Criteria andBack5NotEqualTo(String value) {
            addCriterion("back5 <>", value, "back5");
            return (Criteria) this;
        }

        public Criteria andBack5GreaterThan(String value) {
            addCriterion("back5 >", value, "back5");
            return (Criteria) this;
        }

        public Criteria andBack5GreaterThanOrEqualTo(String value) {
            addCriterion("back5 >=", value, "back5");
            return (Criteria) this;
        }

        public Criteria andBack5LessThan(String value) {
            addCriterion("back5 <", value, "back5");
            return (Criteria) this;
        }

        public Criteria andBack5LessThanOrEqualTo(String value) {
            addCriterion("back5 <=", value, "back5");
            return (Criteria) this;
        }

        public Criteria andBack5Like(String value) {
            addCriterion("back5 like", value, "back5");
            return (Criteria) this;
        }

        public Criteria andBack5NotLike(String value) {
            addCriterion("back5 not like", value, "back5");
            return (Criteria) this;
        }

        public Criteria andBack5In(List<String> values) {
            addCriterion("back5 in", values, "back5");
            return (Criteria) this;
        }

        public Criteria andBack5NotIn(List<String> values) {
            addCriterion("back5 not in", values, "back5");
            return (Criteria) this;
        }

        public Criteria andBack5Between(String value1, String value2) {
            addCriterion("back5 between", value1, value2, "back5");
            return (Criteria) this;
        }

        public Criteria andBack5NotBetween(String value1, String value2) {
            addCriterion("back5 not between", value1, value2, "back5");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table record
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 11 20:57:07 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table record
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}