package com.spring.mpvue.springbootmpvue.mybatis.po;

import java.util.Date;

public class Record {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.ID
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.open_id
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.query_result
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private String queryResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.detail_address
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private String detailAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.build_type
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private String buildType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.area
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.house_type
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private String houseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.indoor_structure
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private String indoorStructure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.floor
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private String floor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.orientation
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private String orientation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.degree_decoration
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private String degreeDecoration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.build_year
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private String buildYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.own_status
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private String ownStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.query_date
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private Date queryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.del_flag
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.dissent
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private String dissent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.expected_price
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private String expectedPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.dissent_reason
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private String dissentReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.back1
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private String back1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.back2
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private Date back2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.back3
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private String back3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.back4
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private String back4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.back5
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    private String back5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.ID
     *
     * @return the value of record.ID
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.ID
     *
     * @param id the value for record.ID
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.open_id
     *
     * @return the value of record.open_id
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.open_id
     *
     * @param openId the value for record.open_id
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.query_result
     *
     * @return the value of record.query_result
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public String getQueryResult() {
        return queryResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.query_result
     *
     * @param queryResult the value for record.query_result
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setQueryResult(String queryResult) {
        this.queryResult = queryResult == null ? null : queryResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.detail_address
     *
     * @return the value of record.detail_address
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public String getDetailAddress() {
        return detailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.detail_address
     *
     * @param detailAddress the value for record.detail_address
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setDetailAddress(String detailAddress) {
        this.detailAddress = detailAddress == null ? null : detailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.build_type
     *
     * @return the value of record.build_type
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public String getBuildType() {
        return buildType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.build_type
     *
     * @param buildType the value for record.build_type
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setBuildType(String buildType) {
        this.buildType = buildType == null ? null : buildType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.area
     *
     * @return the value of record.area
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.area
     *
     * @param area the value for record.area
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.house_type
     *
     * @return the value of record.house_type
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public String getHouseType() {
        return houseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.house_type
     *
     * @param houseType the value for record.house_type
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setHouseType(String houseType) {
        this.houseType = houseType == null ? null : houseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.indoor_structure
     *
     * @return the value of record.indoor_structure
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public String getIndoorStructure() {
        return indoorStructure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.indoor_structure
     *
     * @param indoorStructure the value for record.indoor_structure
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setIndoorStructure(String indoorStructure) {
        this.indoorStructure = indoorStructure == null ? null : indoorStructure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.floor
     *
     * @return the value of record.floor
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public String getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.floor
     *
     * @param floor the value for record.floor
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setFloor(String floor) {
        this.floor = floor == null ? null : floor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.orientation
     *
     * @return the value of record.orientation
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public String getOrientation() {
        return orientation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.orientation
     *
     * @param orientation the value for record.orientation
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setOrientation(String orientation) {
        this.orientation = orientation == null ? null : orientation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.degree_decoration
     *
     * @return the value of record.degree_decoration
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public String getDegreeDecoration() {
        return degreeDecoration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.degree_decoration
     *
     * @param degreeDecoration the value for record.degree_decoration
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setDegreeDecoration(String degreeDecoration) {
        this.degreeDecoration = degreeDecoration == null ? null : degreeDecoration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.build_year
     *
     * @return the value of record.build_year
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public String getBuildYear() {
        return buildYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.build_year
     *
     * @param buildYear the value for record.build_year
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setBuildYear(String buildYear) {
        this.buildYear = buildYear == null ? null : buildYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.own_status
     *
     * @return the value of record.own_status
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public String getOwnStatus() {
        return ownStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.own_status
     *
     * @param ownStatus the value for record.own_status
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setOwnStatus(String ownStatus) {
        this.ownStatus = ownStatus == null ? null : ownStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.query_date
     *
     * @return the value of record.query_date
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public Date getQueryDate() {
        return queryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.query_date
     *
     * @param queryDate the value for record.query_date
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setQueryDate(Date queryDate) {
        this.queryDate = queryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.del_flag
     *
     * @return the value of record.del_flag
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.del_flag
     *
     * @param delFlag the value for record.del_flag
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.dissent
     *
     * @return the value of record.dissent
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public String getDissent() {
        return dissent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.dissent
     *
     * @param dissent the value for record.dissent
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setDissent(String dissent) {
        this.dissent = dissent == null ? null : dissent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.expected_price
     *
     * @return the value of record.expected_price
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public String getExpectedPrice() {
        return expectedPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.expected_price
     *
     * @param expectedPrice the value for record.expected_price
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setExpectedPrice(String expectedPrice) {
        this.expectedPrice = expectedPrice == null ? null : expectedPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.dissent_reason
     *
     * @return the value of record.dissent_reason
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public String getDissentReason() {
        return dissentReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.dissent_reason
     *
     * @param dissentReason the value for record.dissent_reason
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setDissentReason(String dissentReason) {
        this.dissentReason = dissentReason == null ? null : dissentReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.back1
     *
     * @return the value of record.back1
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public String getBack1() {
        return back1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.back1
     *
     * @param back1 the value for record.back1
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setBack1(String back1) {
        this.back1 = back1 == null ? null : back1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.back2
     *
     * @return the value of record.back2
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public Date getBack2() {
        return back2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.back2
     *
     * @param back2 the value for record.back2
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setBack2(Date back2) {
        this.back2 = back2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.back3
     *
     * @return the value of record.back3
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public String getBack3() {
        return back3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.back3
     *
     * @param back3 the value for record.back3
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setBack3(String back3) {
        this.back3 = back3 == null ? null : back3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.back4
     *
     * @return the value of record.back4
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public String getBack4() {
        return back4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.back4
     *
     * @param back4 the value for record.back4
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setBack4(String back4) {
        this.back4 = back4 == null ? null : back4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.back5
     *
     * @return the value of record.back5
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public String getBack5() {
        return back5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.back5
     *
     * @param back5 the value for record.back5
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setBack5(String back5) {
        this.back5 = back5 == null ? null : back5.trim();
    }
}