package com.spring.mpvue.springbootmpvue.mybatis.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ReferencecaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table referencecase
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table referencecase
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table referencecase
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table referencecase
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public ReferencecaseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table referencecase
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table referencecase
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table referencecase
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table referencecase
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table referencecase
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table referencecase
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table referencecase
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table referencecase
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table referencecase
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table referencecase
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table referencecase
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRecordIdIsNull() {
            addCriterion("record_id is null");
            return (Criteria) this;
        }

        public Criteria andRecordIdIsNotNull() {
            addCriterion("record_id is not null");
            return (Criteria) this;
        }

        public Criteria andRecordIdEqualTo(Integer value) {
            addCriterion("record_id =", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdNotEqualTo(Integer value) {
            addCriterion("record_id <>", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdGreaterThan(Integer value) {
            addCriterion("record_id >", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("record_id >=", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdLessThan(Integer value) {
            addCriterion("record_id <", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdLessThanOrEqualTo(Integer value) {
            addCriterion("record_id <=", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdIn(List<Integer> values) {
            addCriterion("record_id in", values, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdNotIn(List<Integer> values) {
            addCriterion("record_id not in", values, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdBetween(Integer value1, Integer value2) {
            addCriterion("record_id between", value1, value2, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdNotBetween(Integer value1, Integer value2) {
            addCriterion("record_id not between", value1, value2, "recordId");
            return (Criteria) this;
        }

        public Criteria andGjsdIsNull() {
            addCriterion("gjsd is null");
            return (Criteria) this;
        }

        public Criteria andGjsdIsNotNull() {
            addCriterion("gjsd is not null");
            return (Criteria) this;
        }

        public Criteria andGjsdEqualTo(Date value) {
            addCriterion("gjsd =", value, "gjsd");
            return (Criteria) this;
        }

        public Criteria andGjsdNotEqualTo(Date value) {
            addCriterion("gjsd <>", value, "gjsd");
            return (Criteria) this;
        }

        public Criteria andGjsdGreaterThan(Date value) {
            addCriterion("gjsd >", value, "gjsd");
            return (Criteria) this;
        }

        public Criteria andGjsdGreaterThanOrEqualTo(Date value) {
            addCriterion("gjsd >=", value, "gjsd");
            return (Criteria) this;
        }

        public Criteria andGjsdLessThan(Date value) {
            addCriterion("gjsd <", value, "gjsd");
            return (Criteria) this;
        }

        public Criteria andGjsdLessThanOrEqualTo(Date value) {
            addCriterion("gjsd <=", value, "gjsd");
            return (Criteria) this;
        }

        public Criteria andGjsdIn(List<Date> values) {
            addCriterion("gjsd in", values, "gjsd");
            return (Criteria) this;
        }

        public Criteria andGjsdNotIn(List<Date> values) {
            addCriterion("gjsd not in", values, "gjsd");
            return (Criteria) this;
        }

        public Criteria andGjsdBetween(Date value1, Date value2) {
            addCriterion("gjsd between", value1, value2, "gjsd");
            return (Criteria) this;
        }

        public Criteria andGjsdNotBetween(Date value1, Date value2) {
            addCriterion("gjsd not between", value1, value2, "gjsd");
            return (Criteria) this;
        }

        public Criteria andRsDzIsNull() {
            addCriterion("rs_dz is null");
            return (Criteria) this;
        }

        public Criteria andRsDzIsNotNull() {
            addCriterion("rs_dz is not null");
            return (Criteria) this;
        }

        public Criteria andRsDzEqualTo(String value) {
            addCriterion("rs_dz =", value, "rsDz");
            return (Criteria) this;
        }

        public Criteria andRsDzNotEqualTo(String value) {
            addCriterion("rs_dz <>", value, "rsDz");
            return (Criteria) this;
        }

        public Criteria andRsDzGreaterThan(String value) {
            addCriterion("rs_dz >", value, "rsDz");
            return (Criteria) this;
        }

        public Criteria andRsDzGreaterThanOrEqualTo(String value) {
            addCriterion("rs_dz >=", value, "rsDz");
            return (Criteria) this;
        }

        public Criteria andRsDzLessThan(String value) {
            addCriterion("rs_dz <", value, "rsDz");
            return (Criteria) this;
        }

        public Criteria andRsDzLessThanOrEqualTo(String value) {
            addCriterion("rs_dz <=", value, "rsDz");
            return (Criteria) this;
        }

        public Criteria andRsDzLike(String value) {
            addCriterion("rs_dz like", value, "rsDz");
            return (Criteria) this;
        }

        public Criteria andRsDzNotLike(String value) {
            addCriterion("rs_dz not like", value, "rsDz");
            return (Criteria) this;
        }

        public Criteria andRsDzIn(List<String> values) {
            addCriterion("rs_dz in", values, "rsDz");
            return (Criteria) this;
        }

        public Criteria andRsDzNotIn(List<String> values) {
            addCriterion("rs_dz not in", values, "rsDz");
            return (Criteria) this;
        }

        public Criteria andRsDzBetween(String value1, String value2) {
            addCriterion("rs_dz between", value1, value2, "rsDz");
            return (Criteria) this;
        }

        public Criteria andRsDzNotBetween(String value1, String value2) {
            addCriterion("rs_dz not between", value1, value2, "rsDz");
            return (Criteria) this;
        }

        public Criteria andBuildIsNull() {
            addCriterion("build is null");
            return (Criteria) this;
        }

        public Criteria andBuildIsNotNull() {
            addCriterion("build is not null");
            return (Criteria) this;
        }

        public Criteria andBuildEqualTo(String value) {
            addCriterion("build =", value, "build");
            return (Criteria) this;
        }

        public Criteria andBuildNotEqualTo(String value) {
            addCriterion("build <>", value, "build");
            return (Criteria) this;
        }

        public Criteria andBuildGreaterThan(String value) {
            addCriterion("build >", value, "build");
            return (Criteria) this;
        }

        public Criteria andBuildGreaterThanOrEqualTo(String value) {
            addCriterion("build >=", value, "build");
            return (Criteria) this;
        }

        public Criteria andBuildLessThan(String value) {
            addCriterion("build <", value, "build");
            return (Criteria) this;
        }

        public Criteria andBuildLessThanOrEqualTo(String value) {
            addCriterion("build <=", value, "build");
            return (Criteria) this;
        }

        public Criteria andBuildLike(String value) {
            addCriterion("build like", value, "build");
            return (Criteria) this;
        }

        public Criteria andBuildNotLike(String value) {
            addCriterion("build not like", value, "build");
            return (Criteria) this;
        }

        public Criteria andBuildIn(List<String> values) {
            addCriterion("build in", values, "build");
            return (Criteria) this;
        }

        public Criteria andBuildNotIn(List<String> values) {
            addCriterion("build not in", values, "build");
            return (Criteria) this;
        }

        public Criteria andBuildBetween(String value1, String value2) {
            addCriterion("build between", value1, value2, "build");
            return (Criteria) this;
        }

        public Criteria andBuildNotBetween(String value1, String value2) {
            addCriterion("build not between", value1, value2, "build");
            return (Criteria) this;
        }

        public Criteria andLcIsNull() {
            addCriterion("lc is null");
            return (Criteria) this;
        }

        public Criteria andLcIsNotNull() {
            addCriterion("lc is not null");
            return (Criteria) this;
        }

        public Criteria andLcEqualTo(String value) {
            addCriterion("lc =", value, "lc");
            return (Criteria) this;
        }

        public Criteria andLcNotEqualTo(String value) {
            addCriterion("lc <>", value, "lc");
            return (Criteria) this;
        }

        public Criteria andLcGreaterThan(String value) {
            addCriterion("lc >", value, "lc");
            return (Criteria) this;
        }

        public Criteria andLcGreaterThanOrEqualTo(String value) {
            addCriterion("lc >=", value, "lc");
            return (Criteria) this;
        }

        public Criteria andLcLessThan(String value) {
            addCriterion("lc <", value, "lc");
            return (Criteria) this;
        }

        public Criteria andLcLessThanOrEqualTo(String value) {
            addCriterion("lc <=", value, "lc");
            return (Criteria) this;
        }

        public Criteria andLcLike(String value) {
            addCriterion("lc like", value, "lc");
            return (Criteria) this;
        }

        public Criteria andLcNotLike(String value) {
            addCriterion("lc not like", value, "lc");
            return (Criteria) this;
        }

        public Criteria andLcIn(List<String> values) {
            addCriterion("lc in", values, "lc");
            return (Criteria) this;
        }

        public Criteria andLcNotIn(List<String> values) {
            addCriterion("lc not in", values, "lc");
            return (Criteria) this;
        }

        public Criteria andLcBetween(String value1, String value2) {
            addCriterion("lc between", value1, value2, "lc");
            return (Criteria) this;
        }

        public Criteria andLcNotBetween(String value1, String value2) {
            addCriterion("lc not between", value1, value2, "lc");
            return (Criteria) this;
        }

        public Criteria andPmIsNull() {
            addCriterion("pm is null");
            return (Criteria) this;
        }

        public Criteria andPmIsNotNull() {
            addCriterion("pm is not null");
            return (Criteria) this;
        }

        public Criteria andPmEqualTo(String value) {
            addCriterion("pm =", value, "pm");
            return (Criteria) this;
        }

        public Criteria andPmNotEqualTo(String value) {
            addCriterion("pm <>", value, "pm");
            return (Criteria) this;
        }

        public Criteria andPmGreaterThan(String value) {
            addCriterion("pm >", value, "pm");
            return (Criteria) this;
        }

        public Criteria andPmGreaterThanOrEqualTo(String value) {
            addCriterion("pm >=", value, "pm");
            return (Criteria) this;
        }

        public Criteria andPmLessThan(String value) {
            addCriterion("pm <", value, "pm");
            return (Criteria) this;
        }

        public Criteria andPmLessThanOrEqualTo(String value) {
            addCriterion("pm <=", value, "pm");
            return (Criteria) this;
        }

        public Criteria andPmLike(String value) {
            addCriterion("pm like", value, "pm");
            return (Criteria) this;
        }

        public Criteria andPmNotLike(String value) {
            addCriterion("pm not like", value, "pm");
            return (Criteria) this;
        }

        public Criteria andPmIn(List<String> values) {
            addCriterion("pm in", values, "pm");
            return (Criteria) this;
        }

        public Criteria andPmNotIn(List<String> values) {
            addCriterion("pm not in", values, "pm");
            return (Criteria) this;
        }

        public Criteria andPmBetween(String value1, String value2) {
            addCriterion("pm between", value1, value2, "pm");
            return (Criteria) this;
        }

        public Criteria andPmNotBetween(String value1, String value2) {
            addCriterion("pm not between", value1, value2, "pm");
            return (Criteria) this;
        }

        public Criteria andCxIsNull() {
            addCriterion("cx is null");
            return (Criteria) this;
        }

        public Criteria andCxIsNotNull() {
            addCriterion("cx is not null");
            return (Criteria) this;
        }

        public Criteria andCxEqualTo(String value) {
            addCriterion("cx =", value, "cx");
            return (Criteria) this;
        }

        public Criteria andCxNotEqualTo(String value) {
            addCriterion("cx <>", value, "cx");
            return (Criteria) this;
        }

        public Criteria andCxGreaterThan(String value) {
            addCriterion("cx >", value, "cx");
            return (Criteria) this;
        }

        public Criteria andCxGreaterThanOrEqualTo(String value) {
            addCriterion("cx >=", value, "cx");
            return (Criteria) this;
        }

        public Criteria andCxLessThan(String value) {
            addCriterion("cx <", value, "cx");
            return (Criteria) this;
        }

        public Criteria andCxLessThanOrEqualTo(String value) {
            addCriterion("cx <=", value, "cx");
            return (Criteria) this;
        }

        public Criteria andCxLike(String value) {
            addCriterion("cx like", value, "cx");
            return (Criteria) this;
        }

        public Criteria andCxNotLike(String value) {
            addCriterion("cx not like", value, "cx");
            return (Criteria) this;
        }

        public Criteria andCxIn(List<String> values) {
            addCriterion("cx in", values, "cx");
            return (Criteria) this;
        }

        public Criteria andCxNotIn(List<String> values) {
            addCriterion("cx not in", values, "cx");
            return (Criteria) this;
        }

        public Criteria andCxBetween(String value1, String value2) {
            addCriterion("cx between", value1, value2, "cx");
            return (Criteria) this;
        }

        public Criteria andCxNotBetween(String value1, String value2) {
            addCriterion("cx not between", value1, value2, "cx");
            return (Criteria) this;
        }

        public Criteria andRjMjIsNull() {
            addCriterion("rj_mj is null");
            return (Criteria) this;
        }

        public Criteria andRjMjIsNotNull() {
            addCriterion("rj_mj is not null");
            return (Criteria) this;
        }

        public Criteria andRjMjEqualTo(String value) {
            addCriterion("rj_mj =", value, "rjMj");
            return (Criteria) this;
        }

        public Criteria andRjMjNotEqualTo(String value) {
            addCriterion("rj_mj <>", value, "rjMj");
            return (Criteria) this;
        }

        public Criteria andRjMjGreaterThan(String value) {
            addCriterion("rj_mj >", value, "rjMj");
            return (Criteria) this;
        }

        public Criteria andRjMjGreaterThanOrEqualTo(String value) {
            addCriterion("rj_mj >=", value, "rjMj");
            return (Criteria) this;
        }

        public Criteria andRjMjLessThan(String value) {
            addCriterion("rj_mj <", value, "rjMj");
            return (Criteria) this;
        }

        public Criteria andRjMjLessThanOrEqualTo(String value) {
            addCriterion("rj_mj <=", value, "rjMj");
            return (Criteria) this;
        }

        public Criteria andRjMjLike(String value) {
            addCriterion("rj_mj like", value, "rjMj");
            return (Criteria) this;
        }

        public Criteria andRjMjNotLike(String value) {
            addCriterion("rj_mj not like", value, "rjMj");
            return (Criteria) this;
        }

        public Criteria andRjMjIn(List<String> values) {
            addCriterion("rj_mj in", values, "rjMj");
            return (Criteria) this;
        }

        public Criteria andRjMjNotIn(List<String> values) {
            addCriterion("rj_mj not in", values, "rjMj");
            return (Criteria) this;
        }

        public Criteria andRjMjBetween(String value1, String value2) {
            addCriterion("rj_mj between", value1, value2, "rjMj");
            return (Criteria) this;
        }

        public Criteria andRjMjNotBetween(String value1, String value2) {
            addCriterion("rj_mj not between", value1, value2, "rjMj");
            return (Criteria) this;
        }

        public Criteria andZxIsNull() {
            addCriterion("zx is null");
            return (Criteria) this;
        }

        public Criteria andZxIsNotNull() {
            addCriterion("zx is not null");
            return (Criteria) this;
        }

        public Criteria andZxEqualTo(String value) {
            addCriterion("zx =", value, "zx");
            return (Criteria) this;
        }

        public Criteria andZxNotEqualTo(String value) {
            addCriterion("zx <>", value, "zx");
            return (Criteria) this;
        }

        public Criteria andZxGreaterThan(String value) {
            addCriterion("zx >", value, "zx");
            return (Criteria) this;
        }

        public Criteria andZxGreaterThanOrEqualTo(String value) {
            addCriterion("zx >=", value, "zx");
            return (Criteria) this;
        }

        public Criteria andZxLessThan(String value) {
            addCriterion("zx <", value, "zx");
            return (Criteria) this;
        }

        public Criteria andZxLessThanOrEqualTo(String value) {
            addCriterion("zx <=", value, "zx");
            return (Criteria) this;
        }

        public Criteria andZxLike(String value) {
            addCriterion("zx like", value, "zx");
            return (Criteria) this;
        }

        public Criteria andZxNotLike(String value) {
            addCriterion("zx not like", value, "zx");
            return (Criteria) this;
        }

        public Criteria andZxIn(List<String> values) {
            addCriterion("zx in", values, "zx");
            return (Criteria) this;
        }

        public Criteria andZxNotIn(List<String> values) {
            addCriterion("zx not in", values, "zx");
            return (Criteria) this;
        }

        public Criteria andZxBetween(String value1, String value2) {
            addCriterion("zx between", value1, value2, "zx");
            return (Criteria) this;
        }

        public Criteria andZxNotBetween(String value1, String value2) {
            addCriterion("zx not between", value1, value2, "zx");
            return (Criteria) this;
        }

        public Criteria andWqIsNull() {
            addCriterion("wq is null");
            return (Criteria) this;
        }

        public Criteria andWqIsNotNull() {
            addCriterion("wq is not null");
            return (Criteria) this;
        }

        public Criteria andWqEqualTo(String value) {
            addCriterion("wq =", value, "wq");
            return (Criteria) this;
        }

        public Criteria andWqNotEqualTo(String value) {
            addCriterion("wq <>", value, "wq");
            return (Criteria) this;
        }

        public Criteria andWqGreaterThan(String value) {
            addCriterion("wq >", value, "wq");
            return (Criteria) this;
        }

        public Criteria andWqGreaterThanOrEqualTo(String value) {
            addCriterion("wq >=", value, "wq");
            return (Criteria) this;
        }

        public Criteria andWqLessThan(String value) {
            addCriterion("wq <", value, "wq");
            return (Criteria) this;
        }

        public Criteria andWqLessThanOrEqualTo(String value) {
            addCriterion("wq <=", value, "wq");
            return (Criteria) this;
        }

        public Criteria andWqLike(String value) {
            addCriterion("wq like", value, "wq");
            return (Criteria) this;
        }

        public Criteria andWqNotLike(String value) {
            addCriterion("wq not like", value, "wq");
            return (Criteria) this;
        }

        public Criteria andWqIn(List<String> values) {
            addCriterion("wq in", values, "wq");
            return (Criteria) this;
        }

        public Criteria andWqNotIn(List<String> values) {
            addCriterion("wq not in", values, "wq");
            return (Criteria) this;
        }

        public Criteria andWqBetween(String value1, String value2) {
            addCriterion("wq between", value1, value2, "wq");
            return (Criteria) this;
        }

        public Criteria andWqNotBetween(String value1, String value2) {
            addCriterion("wq not between", value1, value2, "wq");
            return (Criteria) this;
        }

        public Criteria andCompletedateIsNull() {
            addCriterion("completeDate is null");
            return (Criteria) this;
        }

        public Criteria andCompletedateIsNotNull() {
            addCriterion("completeDate is not null");
            return (Criteria) this;
        }

        public Criteria andCompletedateEqualTo(String value) {
            addCriterion("completeDate =", value, "completedate");
            return (Criteria) this;
        }

        public Criteria andCompletedateNotEqualTo(String value) {
            addCriterion("completeDate <>", value, "completedate");
            return (Criteria) this;
        }

        public Criteria andCompletedateGreaterThan(String value) {
            addCriterion("completeDate >", value, "completedate");
            return (Criteria) this;
        }

        public Criteria andCompletedateGreaterThanOrEqualTo(String value) {
            addCriterion("completeDate >=", value, "completedate");
            return (Criteria) this;
        }

        public Criteria andCompletedateLessThan(String value) {
            addCriterion("completeDate <", value, "completedate");
            return (Criteria) this;
        }

        public Criteria andCompletedateLessThanOrEqualTo(String value) {
            addCriterion("completeDate <=", value, "completedate");
            return (Criteria) this;
        }

        public Criteria andCompletedateLike(String value) {
            addCriterion("completeDate like", value, "completedate");
            return (Criteria) this;
        }

        public Criteria andCompletedateNotLike(String value) {
            addCriterion("completeDate not like", value, "completedate");
            return (Criteria) this;
        }

        public Criteria andCompletedateIn(List<String> values) {
            addCriterion("completeDate in", values, "completedate");
            return (Criteria) this;
        }

        public Criteria andCompletedateNotIn(List<String> values) {
            addCriterion("completeDate not in", values, "completedate");
            return (Criteria) this;
        }

        public Criteria andCompletedateBetween(String value1, String value2) {
            addCriterion("completeDate between", value1, value2, "completedate");
            return (Criteria) this;
        }

        public Criteria andCompletedateNotBetween(String value1, String value2) {
            addCriterion("completeDate not between", value1, value2, "completedate");
            return (Criteria) this;
        }

        public Criteria andJgIsNull() {
            addCriterion("jg is null");
            return (Criteria) this;
        }

        public Criteria andJgIsNotNull() {
            addCriterion("jg is not null");
            return (Criteria) this;
        }

        public Criteria andJgEqualTo(String value) {
            addCriterion("jg =", value, "jg");
            return (Criteria) this;
        }

        public Criteria andJgNotEqualTo(String value) {
            addCriterion("jg <>", value, "jg");
            return (Criteria) this;
        }

        public Criteria andJgGreaterThan(String value) {
            addCriterion("jg >", value, "jg");
            return (Criteria) this;
        }

        public Criteria andJgGreaterThanOrEqualTo(String value) {
            addCriterion("jg >=", value, "jg");
            return (Criteria) this;
        }

        public Criteria andJgLessThan(String value) {
            addCriterion("jg <", value, "jg");
            return (Criteria) this;
        }

        public Criteria andJgLessThanOrEqualTo(String value) {
            addCriterion("jg <=", value, "jg");
            return (Criteria) this;
        }

        public Criteria andJgLike(String value) {
            addCriterion("jg like", value, "jg");
            return (Criteria) this;
        }

        public Criteria andJgNotLike(String value) {
            addCriterion("jg not like", value, "jg");
            return (Criteria) this;
        }

        public Criteria andJgIn(List<String> values) {
            addCriterion("jg in", values, "jg");
            return (Criteria) this;
        }

        public Criteria andJgNotIn(List<String> values) {
            addCriterion("jg not in", values, "jg");
            return (Criteria) this;
        }

        public Criteria andJgBetween(String value1, String value2) {
            addCriterion("jg between", value1, value2, "jg");
            return (Criteria) this;
        }

        public Criteria andJgNotBetween(String value1, String value2) {
            addCriterion("jg not between", value1, value2, "jg");
            return (Criteria) this;
        }

        public Criteria andYtIsNull() {
            addCriterion("yt is null");
            return (Criteria) this;
        }

        public Criteria andYtIsNotNull() {
            addCriterion("yt is not null");
            return (Criteria) this;
        }

        public Criteria andYtEqualTo(String value) {
            addCriterion("yt =", value, "yt");
            return (Criteria) this;
        }

        public Criteria andYtNotEqualTo(String value) {
            addCriterion("yt <>", value, "yt");
            return (Criteria) this;
        }

        public Criteria andYtGreaterThan(String value) {
            addCriterion("yt >", value, "yt");
            return (Criteria) this;
        }

        public Criteria andYtGreaterThanOrEqualTo(String value) {
            addCriterion("yt >=", value, "yt");
            return (Criteria) this;
        }

        public Criteria andYtLessThan(String value) {
            addCriterion("yt <", value, "yt");
            return (Criteria) this;
        }

        public Criteria andYtLessThanOrEqualTo(String value) {
            addCriterion("yt <=", value, "yt");
            return (Criteria) this;
        }

        public Criteria andYtLike(String value) {
            addCriterion("yt like", value, "yt");
            return (Criteria) this;
        }

        public Criteria andYtNotLike(String value) {
            addCriterion("yt not like", value, "yt");
            return (Criteria) this;
        }

        public Criteria andYtIn(List<String> values) {
            addCriterion("yt in", values, "yt");
            return (Criteria) this;
        }

        public Criteria andYtNotIn(List<String> values) {
            addCriterion("yt not in", values, "yt");
            return (Criteria) this;
        }

        public Criteria andYtBetween(String value1, String value2) {
            addCriterion("yt between", value1, value2, "yt");
            return (Criteria) this;
        }

        public Criteria andYtNotBetween(String value1, String value2) {
            addCriterion("yt not between", value1, value2, "yt");
            return (Criteria) this;
        }

        public Criteria andBack1IsNull() {
            addCriterion("back1 is null");
            return (Criteria) this;
        }

        public Criteria andBack1IsNotNull() {
            addCriterion("back1 is not null");
            return (Criteria) this;
        }

        public Criteria andBack1EqualTo(String value) {
            addCriterion("back1 =", value, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1NotEqualTo(String value) {
            addCriterion("back1 <>", value, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1GreaterThan(String value) {
            addCriterion("back1 >", value, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1GreaterThanOrEqualTo(String value) {
            addCriterion("back1 >=", value, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1LessThan(String value) {
            addCriterion("back1 <", value, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1LessThanOrEqualTo(String value) {
            addCriterion("back1 <=", value, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1Like(String value) {
            addCriterion("back1 like", value, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1NotLike(String value) {
            addCriterion("back1 not like", value, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1In(List<String> values) {
            addCriterion("back1 in", values, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1NotIn(List<String> values) {
            addCriterion("back1 not in", values, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1Between(String value1, String value2) {
            addCriterion("back1 between", value1, value2, "back1");
            return (Criteria) this;
        }

        public Criteria andBack1NotBetween(String value1, String value2) {
            addCriterion("back1 not between", value1, value2, "back1");
            return (Criteria) this;
        }

        public Criteria andBack2IsNull() {
            addCriterion("back2 is null");
            return (Criteria) this;
        }

        public Criteria andBack2IsNotNull() {
            addCriterion("back2 is not null");
            return (Criteria) this;
        }

        public Criteria andBack2EqualTo(String value) {
            addCriterion("back2 =", value, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2NotEqualTo(String value) {
            addCriterion("back2 <>", value, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2GreaterThan(String value) {
            addCriterion("back2 >", value, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2GreaterThanOrEqualTo(String value) {
            addCriterion("back2 >=", value, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2LessThan(String value) {
            addCriterion("back2 <", value, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2LessThanOrEqualTo(String value) {
            addCriterion("back2 <=", value, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2Like(String value) {
            addCriterion("back2 like", value, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2NotLike(String value) {
            addCriterion("back2 not like", value, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2In(List<String> values) {
            addCriterion("back2 in", values, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2NotIn(List<String> values) {
            addCriterion("back2 not in", values, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2Between(String value1, String value2) {
            addCriterion("back2 between", value1, value2, "back2");
            return (Criteria) this;
        }

        public Criteria andBack2NotBetween(String value1, String value2) {
            addCriterion("back2 not between", value1, value2, "back2");
            return (Criteria) this;
        }

        public Criteria andBack3IsNull() {
            addCriterion("back3 is null");
            return (Criteria) this;
        }

        public Criteria andBack3IsNotNull() {
            addCriterion("back3 is not null");
            return (Criteria) this;
        }

        public Criteria andBack3EqualTo(String value) {
            addCriterion("back3 =", value, "back3");
            return (Criteria) this;
        }

        public Criteria andBack3NotEqualTo(String value) {
            addCriterion("back3 <>", value, "back3");
            return (Criteria) this;
        }

        public Criteria andBack3GreaterThan(String value) {
            addCriterion("back3 >", value, "back3");
            return (Criteria) this;
        }

        public Criteria andBack3GreaterThanOrEqualTo(String value) {
            addCriterion("back3 >=", value, "back3");
            return (Criteria) this;
        }

        public Criteria andBack3LessThan(String value) {
            addCriterion("back3 <", value, "back3");
            return (Criteria) this;
        }

        public Criteria andBack3LessThanOrEqualTo(String value) {
            addCriterion("back3 <=", value, "back3");
            return (Criteria) this;
        }

        public Criteria andBack3Like(String value) {
            addCriterion("back3 like", value, "back3");
            return (Criteria) this;
        }

        public Criteria andBack3NotLike(String value) {
            addCriterion("back3 not like", value, "back3");
            return (Criteria) this;
        }

        public Criteria andBack3In(List<String> values) {
            addCriterion("back3 in", values, "back3");
            return (Criteria) this;
        }

        public Criteria andBack3NotIn(List<String> values) {
            addCriterion("back3 not in", values, "back3");
            return (Criteria) this;
        }

        public Criteria andBack3Between(String value1, String value2) {
            addCriterion("back3 between", value1, value2, "back3");
            return (Criteria) this;
        }

        public Criteria andBack3NotBetween(String value1, String value2) {
            addCriterion("back3 not between", value1, value2, "back3");
            return (Criteria) this;
        }

        public Criteria andBack4IsNull() {
            addCriterion("back4 is null");
            return (Criteria) this;
        }

        public Criteria andBack4IsNotNull() {
            addCriterion("back4 is not null");
            return (Criteria) this;
        }

        public Criteria andBack4EqualTo(String value) {
            addCriterion("back4 =", value, "back4");
            return (Criteria) this;
        }

        public Criteria andBack4NotEqualTo(String value) {
            addCriterion("back4 <>", value, "back4");
            return (Criteria) this;
        }

        public Criteria andBack4GreaterThan(String value) {
            addCriterion("back4 >", value, "back4");
            return (Criteria) this;
        }

        public Criteria andBack4GreaterThanOrEqualTo(String value) {
            addCriterion("back4 >=", value, "back4");
            return (Criteria) this;
        }

        public Criteria andBack4LessThan(String value) {
            addCriterion("back4 <", value, "back4");
            return (Criteria) this;
        }

        public Criteria andBack4LessThanOrEqualTo(String value) {
            addCriterion("back4 <=", value, "back4");
            return (Criteria) this;
        }

        public Criteria andBack4Like(String value) {
            addCriterion("back4 like", value, "back4");
            return (Criteria) this;
        }

        public Criteria andBack4NotLike(String value) {
            addCriterion("back4 not like", value, "back4");
            return (Criteria) this;
        }

        public Criteria andBack4In(List<String> values) {
            addCriterion("back4 in", values, "back4");
            return (Criteria) this;
        }

        public Criteria andBack4NotIn(List<String> values) {
            addCriterion("back4 not in", values, "back4");
            return (Criteria) this;
        }

        public Criteria andBack4Between(String value1, String value2) {
            addCriterion("back4 between", value1, value2, "back4");
            return (Criteria) this;
        }

        public Criteria andBack4NotBetween(String value1, String value2) {
            addCriterion("back4 not between", value1, value2, "back4");
            return (Criteria) this;
        }

        public Criteria andBack5IsNull() {
            addCriterion("back5 is null");
            return (Criteria) this;
        }

        public Criteria andBack5IsNotNull() {
            addCriterion("back5 is not null");
            return (Criteria) this;
        }

        public Criteria andBack5EqualTo(Date value) {
            addCriterion("back5 =", value, "back5");
            return (Criteria) this;
        }

        public Criteria andBack5NotEqualTo(Date value) {
            addCriterion("back5 <>", value, "back5");
            return (Criteria) this;
        }

        public Criteria andBack5GreaterThan(Date value) {
            addCriterion("back5 >", value, "back5");
            return (Criteria) this;
        }

        public Criteria andBack5GreaterThanOrEqualTo(Date value) {
            addCriterion("back5 >=", value, "back5");
            return (Criteria) this;
        }

        public Criteria andBack5LessThan(Date value) {
            addCriterion("back5 <", value, "back5");
            return (Criteria) this;
        }

        public Criteria andBack5LessThanOrEqualTo(Date value) {
            addCriterion("back5 <=", value, "back5");
            return (Criteria) this;
        }

        public Criteria andBack5In(List<Date> values) {
            addCriterion("back5 in", values, "back5");
            return (Criteria) this;
        }

        public Criteria andBack5NotIn(List<Date> values) {
            addCriterion("back5 not in", values, "back5");
            return (Criteria) this;
        }

        public Criteria andBack5Between(Date value1, Date value2) {
            addCriterion("back5 between", value1, value2, "back5");
            return (Criteria) this;
        }

        public Criteria andBack5NotBetween(Date value1, Date value2) {
            addCriterion("back5 not between", value1, value2, "back5");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table referencecase
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 11 20:57:07 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table referencecase
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}