package com.spring.mpvue.springbootmpvue.mybatis.mapper;

import com.spring.mpvue.springbootmpvue.mybatis.po.Paramconfig;
import com.spring.mpvue.springbootmpvue.mybatis.po.ParamconfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ParamconfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paramconfig
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    int countByExample(ParamconfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paramconfig
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    int deleteByExample(ParamconfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paramconfig
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paramconfig
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    int insert(Paramconfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paramconfig
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    int insertSelective(Paramconfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paramconfig
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    List<Paramconfig> selectByExample(ParamconfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paramconfig
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    Paramconfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paramconfig
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    int updateByExampleSelective(@Param("record") Paramconfig record, @Param("example") ParamconfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paramconfig
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    int updateByExample(@Param("record") Paramconfig record, @Param("example") ParamconfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paramconfig
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    int updateByPrimaryKeySelective(Paramconfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table paramconfig
     *
     * @mbggenerated Mon Mar 11 20:57:07 CST 2019
     */
    int updateByPrimaryKey(Paramconfig record);
}