server:
  port: 8082
  servlet:
    context-path: /evaluate
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/dbspringboot?useUnicode=true&characterEncoding=utf8&useSSL=true
        username: root
        password: 12345a
#自定义配置
resources:
    logdir: logs/
    midpHost: 1.1.1.1
# swagger配置
swagger:
    isEnable: false
